apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-creator
  namespace: lifecycle
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: service-creator
          restartPolicy: OnFailure
          containers:
            - name: service-creator
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - /scripts/service-creator.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          volumes:
            - name: script-volume
              configMap:
                name: service-creator-script
                defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-creator
  namespace: lifecycle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-creator
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "list", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-creator
subjects:
- kind: ServiceAccount
  name: service-creator
  namespace: lifecycle
roleRef:
  kind: ClusterRole
  name: service-creator
  apiGroup: rbac.authorization.k8s.io