apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  namespace: s3
  labels:
    app: heartbeat
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 32187 
  selector:
    app: heartbeat
