apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zfs.name }}-service
  namespace: {{ .Values.zfs.namespace }}
  labels:
     {{- include "zfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9134
      targetPort: 9134
      protocol: TCP
      name: zfs
  selector:
    {{- include "zfs.selectorLabels" . | nindent 6 }}
