name: Helm CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  lint-and-validate:
    name: Lint and Validate Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.4

      - name: Helm lint
        run: helm lint .

      - name: Helm validate
        run: helm template . --dry-run

  release:
    name: Publish Helm Chart to GitHub Releases
    runs-on: ubuntu-latest
    needs: lint-and-validate 
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.4

      - name: Create Helm package
        run: helm package .

      - name: Create Git Tag
        id: tag
        run: |
          VERSION=$(grep '^version' ./Chart.yaml | cut -d ' ' -f 2)
          echo "Version: $VERSION"
          git config --global user.name "lokesh1306"
          git config --global user.email "challagulla.l@northeastern.edu"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Upload Helm package as GitHub release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tgz"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
